baseurl: "https://lander-hatsune.github.io/"
languageCode: "en-us"
title: "Lander.Notes"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  diary: "/diary/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "posts/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "some of what I learned"
  footer: "&copy; *Lander* 2022 - {Year} | [Github](https://github.com/Lander-Hatsune) | [Email](wang-wx19@mails.tsinghua.edu.cn); Powered by Hugo XMin"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
